### ISSUE TITLE
👮‍♂️ Error handling

### ISSUE THREAD

**Issue by Aidan98** [noyamirai/cmd-online#18]
When users try login or register as a new user they need to  see what errors they get like _"This username already exists", "Make sure your passwords match", etc_

**Comment by noyamirai** [comment]
I agree, I hadn't done much error handling myself since the team generation feature itself prevents errors, however we should just add general styling we could use for all error messages.

Maybe we could think of a way to give users live feedback? So when they are typing a username, and it happens to be taken, the application would instantly show the relevant error message rather than the user having to click on 'submit' first to know whether or not their username is unique? 🤔

**Comment by Aidan98** [comment]
Not sure live feedback is feasible as the page would need to continuously refresh, which costs more data. I'd put that at a very low priority if at all (nice to have). My idea was to create dismissible errors fitting our style.

**Comment by Aidan98** [comment]
Furthermore old browsers would probably not support this🤔.

> Maybe we could think of a way to give users live feedback? So when they are typing a username, and it happens to be taken, the application would instantly show the relevant error message rather than the user having to click on 'submit' first to know whether or not their username is unique? 🤔
